openapi: 3.0.3
info:
  title: not used
  version: not used
paths: { } # remove intellij warning
components:
  schemas:
    ErrorArgument:
      description: Arguments used in the error message.
      properties:
        key:
          type: string
        value:
          type: string
        type:
          type: string
    Error:
      description: Custom error object with translated messages.
      properties:
        time:
          type: string
          format: date-time
        code:
          type: string
        title:
          type: string
        message:
          type: string
        args:
          type: array
          items:
            $ref: "#/components/schemas/ErrorArgument"
