openapi: 3.0.3
info:
  title: not used
  version: not used
paths: { } # remove intellij warning
components:
  parameters:
    pageOptional:
      in: query
      name: page
      description: Pagination parameter. Skips page * size entries.
      required: false
      schema:
        default: 0
        format: int32
        minimum: 0
        type: integer
    sizeOptional:
      name: size
      description: Max number of results per page.
      in: query
      required: false
      schema:
        default: 20
        format: int32
        maximum: 1000
        minimum: 1
        type: integer
    sortOptional:
      name: sort
      description: Paramter to sort by as field(:(asc|desc))?. If missing default sort is used. field is the name in
        the db model not the db field name.
      in: query
      schema:
        type: array
        items:
          type: string
      allowReserved: true

  schemas:
    ArrayMeta:
      description: Used in paginated responses as meta type to have meta info for pagination.
      properties:
        first:
          description: Boolean true if it's the first page.
          type: boolean
          default: false
        last:
          description: Boolean true if it's the last page.
          type: boolean
          default: false
        number:
          description: The requested page.
          type: integer
          format: int32
          minimum: 0
        number_of_elements:
          description: Number of elements on this page.
          type: integer
          format: int32
          minimum: 0
        size:
          description: The requested page size.
          type: integer
          format: int32
          minimum: 0
        total_elements:
          description: Total number of entries matching the query.
          type: integer
          format: int64
          minimum: 0
        total_pages:
          description: Number of pages in total.
          type: integer
          format: int32
          minimum: 0
        sort:
          description: Used values to sort the result.
          type: array
          items:
            type: string
