openapi: 3.0.3
info:
  title: not used
  version: not used
paths: { } # remove intellij warning
components:
  parameters:
    idPathRequired:
      in: path
      name: id
      description: Id of a resource.
      required: true
      schema:
        type: string
        format: uuid