application:
  updater:
    enabled: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        decode404: false
        retryer: dev.mbo.telegrambot.client.retry.NoRetryer
      telegramApi:
        url: https://api.telegram.org
        basePath: ""
  compression:
    request:
      enabled: true
      mime-types: application/json,text/xml,application/xml,text/html
      min-request-size: 2048

logging:
  level:
    root: INFO
    dev.mbo: TRACE
    dev:
      mbo:
        telegrambot:
          updater: DEBUG

server:
  port: 6170
  shutdown: graceful

spring:
  application:
    name: telegram-bot
  main:
    banner-mode: off

clients:
  telegram:
    botToken: notoken